chunk_overlap: 128
chunk_size: 1024
description: Topk=7_RemoveFinalSentence
emb_type: openai
index_name: msk-mri
response_mode: simple_summarize
similarity_top_k: 7
synthesizer_llm: gpt-4
synthesizer_max_tokens: 512
synthesizer_temperature: 0
vectorstore: faiss
