dataset: data/queries/MSK LLM Fictitious Case Files Full - Reorder.csv
description: NoRAG
json_testcases: data/queries/full_testcase_reorder.json
n_iterations: 3
synthesizer_llm: gpt-4
synthesizer_max_tokens: 512
synthesizer_temperature: 0
