chunk_overlap: 20
chunk_size: 512
dataset: data/queries/MSK LLM Fictitious Case Files Full.csv
db_directory: data/emb_store/simple/openai_512_20
description: base_rau_rag-n=5-k=3
index_name: msk_mri
json_testcases: ./data/queries/full_testcase.json
n_iterations: 5
response_mode: compact
similarity_top_k: 3
store_type: simple
synthesizer_llm: gpt-4
synthesizer_max_tokens: 512
synthesizer_temperature: 0
